<?php
/**
 * @file
 * agov_landing_pages.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function agov_landing_pages_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_content'
  $field_bases['field_content'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_content',
    'foreign keys' => array(),
    'indexes' => array(),
    'locked' => 0,
    'module' => 'paragraphs',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'paragraphs',
  );

  // Exported field_base: 'field_hide_sidebars'
  $field_bases['field_hide_sidebars'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_hide_sidebars',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'none' => 'Show sidebars (if present)',
        'all' => 'Hide all sidebars',
        'first' => 'Hide first sidebar',
        'second' => 'Hide second sidebar',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
