<?php
/**
 * @file
 * Code for the Entity layouts feature.
 */

include_once 'agov_entity_layouts.features.inc';

/**
 * Define the normal layout mode.
 */
const AGOV_ENTITY_LAYOUTS_MODE_NORMAL = 'normal';

/**
 * Define the dynamic layout mode.
 */
const AGOV_ENTITY_LAYOUTS_MODE_DYNAMIC = 'paragraphs';

/**
 * Implements hook_entity_view().
 */
function agov_entity_layouts_entity_view($entity, $type, $view_mode, $langcode) {
  \Drupal\agov_entity_layouts\EntityContentizer::init()->entityView($entity, $type, $view_mode, $langcode);
}

/**
 * Callback to provide options for the layout_mode field.
 */
function agov_entity_layouts_layout_mode_options() {

  return array(
    AGOV_ENTITY_LAYOUTS_MODE_NORMAL => t('Normal (default)'),
    AGOV_ENTITY_LAYOUTS_MODE_DYNAMIC => t('Dynamic'),
  );
}
