<?php

/**
 * @file
 * Blank module file
 *
 * @license GPL v2 http://www.fsf.org/licensing/licenses/gpl.html
 * @author Chris Skene chris at previousnext dot com dot au
 * @copyright Copyright(c) 2015 Previous Next Pty Ltd
 */

/**
 * Implements hook_modules_enabled().
 */
function agov_default_arrangements_modules_enabled($modules) {
  if (in_array('agov_default_arrangements', $modules)) {
    _agov_arrangements_default_arrangements();
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function agov_default_arrangements_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'modules_enabled') {
    $module_name = 'agov_default_arrangements';
    $group = $implementations[$module_name];
    unset($implementations[$module_name]);
    $implementations[$module_name] = $group;
  }
}

/**
 * Callback to install some default arrangement types.
 */
function _agov_arrangements_default_arrangements() {
  $arrangements = array(
    'full' => array(
      'title' => 'Full width',
    ),
    'tiles_2' => array(
      'title' => 'Tiled (2 across)',
    ),
    'tiles_3' => array(
      'title' => 'Tiled (3 across)',
    ),
    'tiles_4' => array(
      'title' => 'Tiled (4 across)',
    ),
    'tiles_5' => array(
      'title' => 'Tiled (5 across)',
    ),
  );

  foreach ($arrangements as $arr_key => $settings) {
    $settings['field_machine_name'][LANGUAGE_NONE][0]['value'] = $arr_key;
    $settings['type'] = 'arrangement';
    $entity = entity_create('arrangement', $settings);
    entity_save('arrangement', $entity);
  }
}
