; This file was auto-generated by drush make
core = 8.x
api = 2

defaults[projects][subdir] = "contrib"

; Contrib modules

projects[layout_plugin][version] = 1.0-alpha22
projects[layout_plugin][subdir] = contrib

projects[panels][version] = 3.0-beta2
projects[panels][subdir] = contrib

projects[ctools][version] = 3.0-alpha22
projects[ctools][subdir] = contrib

projects[twitter_block][version] = 2.0
projects[twitter_block][subdir] = contrib

projects[linkicon][subdir] = 'contrib'
projects[linkicon][version] = '1.2'

; Development versions

projects[page_manager][type] = module
projects[page_manager][download][type] = git
projects[page_manager][download][url] = http://git.drupal.org/project/page_manager.git
projects[page_manager][download][branch] = 8.x-1.x
projects[page_manager][download][revision] = 8fa43f74d8ddb6d45f19de536ac61c9a8aea4946
projects[page_manager][subdir] = 'contrib'
; https://www.drupal.org/node/2601004
projects[page_manager][patch][] = https://www.drupal.org/files/issues/page-manager-contextual-temp.patch

projects[token][type] = module
projects[token][download][type] = git
projects[token][download][url] = http://git.drupal.org/project/token.git
projects[token][download][branch] = 8.x-1.x
projects[token][download][revision] = 5a36ca581d4c02d0afead767b48263e29af83824
projects[token][subdir] = 'contrib'

projects[title][type] = module
projects[title][download][type] = git
projects[title][download][url] = http://git.drupal.org/project/title.git
projects[title][download][branch] = 8.x-2.x
projects[title][download][revision] = b163e2d50b3add3842ac67ea11cced5eb5d7ceaf
projects[title][subdir] = 'contrib'

projects[fences][type] = module
projects[fences][download][type] = git
projects[fences][download][url] = http://git.drupal.org/project/fences.git
projects[fences][download][branch] = 8.x-2.x
projects[fences][download][revision] = 17e56ed95b358544e0a93a37b819793234f7876e
projects[fences][subdir] = 'contrib'

; Committed to aGov

;projects[file_entity][type] = module
;projects[file_entity][download][type] = git
;projects[file_entity][download][url] = https://github.com/md-systems/file_entity.git
;projects[file_entity][download][branch] = 8.x-2.x

;projects[pathauto][type] = module
;projects[pathauto][download][type] = git
;projects[pathauto][download][url] = https://github.com/md-systems/pathauto.git
;projects[pathauto][download][branch] = 8.x-1.x
;projects[pathauto][download][revision] = e850af1d33adecd68c9e36274a7b6391a89125eb
;projects[pathauto][subdir] = 'contrib'


; aGov

; Themes

; Libraries

; Development Modules
projects[config_devel][version] = '1.0-rc1'
projects[config_devel][subdir] = 'development'

projects[default_content][type] = module
projects[default_content][download][type] = git
projects[default_content][download][url] = http://git.drupal.org/project/default_content.git
projects[default_content][download][branch] = 8.x-1.x
projects[default_content][download][revision] = 471bf110e40e22b8a5ed10973825959aa33b2f21
projects[default_content][subdir] = 'development'
