; This file was auto-generated by drush make
core = 8.x
api = 2

defaults[projects][subdir] = "contrib"

; Contrib modules
projects[file_entity][type] = module
projects[file_entity][download][type] = git
projects[file_entity][download][url] = https://github.com/md-systems/file_entity.git
projects[file_entity][download][branch] = 8.x-2.x
projects[file_entity][subdir] = 'contrib'

projects[linkicon][subdir] = 'contrib'
projects[linkicon][version] = '1.0'
projects[linkicon][patch][] = https://www.drupal.org/files/issues/linkicon-schema.patch

projects[fences][subdir] = 'contrib'
projects[fences][version] = '2.x'
projects[fences][patch][] = https://www.drupal.org/files/issues/2572477-5.patch


; aGov

; Themes

; Libraries

; Development Modules
projects[config_devel][version] = '1.0-beta4'
projects[config_devel][subdir] = 'development'
projects[default_content][type] = module
projects[default_content][download][type] = git
projects[default_content][download][url] = https://github.com/larowlan/default_content.git
projects[default_content][download][branch] = 8.x
projects[default_content][subdir] = 'development'
